// src/routes-list.js
// Список статических путей для sitemap и пререндера.
// Если появляется новый товар/категория — добавьте сюда вручную,
// либо (лучше) сгенерируйте автоматически из products/crops (см. ниже).

export const staticRoutes = [
    "/",
    "/agrotehnika",
    "/poleznaya-informatsiya",
  ];
  
  export const cropRoutes = [
    "/catalog/tomaty",
    "/catalog/ogurtsy",
    "/catalog/sladkiy-perets",
    "/catalog/tsvetnaya-kapusta",
    "/catalog/kapusta",
    "/catalog/sladkaya-kukuruza",
    "/catalog/bakhchevye-kultury",
    "/catalog/zeleni",
    "/catalog/kormovaya-kukuruza",
  ];
  
  export const productRoutes = [
    "/catalog/tomaty/canova-f1",
    "/catalog/tomaty/arirang-f1",
    "/catalog/tomaty/debut-f1",
    "/catalog/tomaty/tomaris-f1",
    "/catalog/tomaty/pinkball-f1",
    "/catalog/tomaty/pinksweet-f1",
    "/catalog/tomaty/chereza-f1",
    "/catalog/tomaty/tornado-f1",
    "/catalog/tomaty/aurora-f1",
    "/catalog/tomaty/pink-flash-f1",
    "/catalog/tomaty/dyno-f1",
    "/catalog/tomaty/vega-f1",
    "/catalog/tomaty/nova-f1",
    "/catalog/tomaty/strombolino-f1",
    "/catalog/tomaty/daterino-f1",
    "/catalog/tomaty/briscolino-f1",
    "/catalog/tomaty/ug-6101-f1",
    "/catalog/tomaty/madera",
    "/catalog/tomaty/king-rock",
    "/catalog/tomaty/kingston",
    "/catalog/tomaty/h2274",
    "/catalog/tomaty/rio-grande",
    "/catalog/tomaty/maxi-rio",
    "/catalog/ogurtsy/fontina-f1",
    "/catalog/ogurtsy/avante-f1",
    "/catalog/ogurtsy/espero-f1",
    "/catalog/ogurtsy/collins-f1",
    "/catalog/ogurtsy/ballistic-f1",
    "/catalog/ogurtsy/bazooka-f1",
    "/catalog/ogurtsy/nw6063-f1",
    "/catalog/ogurtsy/oliver-f1",
    "/catalog/ogurtsy/officer-f1",
    "/catalog/ogurtsy/apolo-f1",
    "/catalog/ogurtsy/zico-f1",
    "/catalog/ogurtsy/cu35641-f1",
    "/catalog/sladkiy-perets/karisma-f1",
    "/catalog/sladkiy-perets/amarok-f1",
    "/catalog/sladkiy-perets/vanguard-f1",
    "/catalog/sladkiy-perets/hercules-f1",
    "/catalog/sladkiy-perets/oida-f1",
    "/catalog/tsvetnaya-kapusta/galiote-f1",
    "/catalog/tsvetnaya-kapusta/obito-f1",
    "/catalog/tsvetnaya-kapusta/ardent-f1",
    "/catalog/tsvetnaya-kapusta/thalassa-f1",
    "/catalog/tsvetnaya-kapusta/mignon-f1",
    "/catalog/tsvetnaya-kapusta/clipper-f1",
    "/catalog/kapusta/fora-f1",
    "/catalog/kapusta/surkhan-f1",
    "/catalog/kapusta/bingo-f1",
    "/catalog/kapusta/centurion-f1",
    "/catalog/kapusta/red-sky-f1",
    "/catalog/sladkaya-kukuruza/832-f1",
    "/catalog/sladkaya-kukuruza/driver-f1",
    "/catalog/sladkaya-kukuruza/turbine-f1",
    "/catalog/sladkaya-kukuruza/higlow-52-f1",
    "/catalog/sladkaya-kukuruza/tyson-f1",
    "/catalog/bakhchevye-kultury/impresa-f1",
    "/catalog/bakhchevye-kultury/maradona-f1",
    "/catalog/bakhchevye-kultury/super-crimson",
    "/catalog/bakhchevye-kultury/au-producer",
    "/catalog/zeleni/primaris",
    "/catalog/zeleni/novas",
    "/catalog/zeleni/robust",
    "/catalog/kormovaya-kukuruza/dms-3111",
    "/catalog/kormovaya-kukuruza/dms-3477",
    "/catalog/kormovaya-kukuruza/agm-1403",
  ];
  
  export const allRoutes = [...staticRoutes, ...cropRoutes, ...productRoutes];